# Session 2 & 3 Data Analytics: Python Basics

# Variables 

If you are working with files stored in your Google Drive, you will need to set your working directory in Colab to the location of your notebook. This is because the default working directory in the Colab environment is not the same as where your notebook is saved in your Drive.

The code in the following cells will first connect your Colab session to your Google Drive and then change the current working directory to the location of this notebook file.

**Note:** if you are working locally with VSCode the default directory will be the one where your notebook is located and you don't need to run the two cells below. 

In [ ]:
# Code to access drive
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Set working directory to proper location
import os
os.chdir("/content/drive/MyDrive/Colab Notebooks/Data Analytics/Session 2 & 3")

## Numeric Variables

### Definition

In [2]:
# assign integer variable
x = 3 
print(type(x))

<class 'int'>


In [3]:
# assign float variable
x = 3.0
print(type(x))

<class 'float'>


### Arithmetic operators

In [4]:
# arithmetic operators
x = 5.
y = 3.
print("addition: ", x + y) 
print("subtraction: ", x - y)  
print("multiplication: ", x * y)
print("division: ", x / y) 
print("modulus: ", x % y)  
print("floor division: ", x // y) 
print("exponent: ", x ** y) 

addition:  8.0
subtraction:  2.0
multiplication:  15.0
division:  1.6666666666666667
modulus:  2.0
floor division:  1.0
exponent:  125.0


In [6]:
# integer division (no issues from python 3.X onwards)
x = 5
y = 3
print(x / y)

1.6666666666666667


In [7]:
# float division (no need to type cast from python 3.X onwards)
x = 5.
y = 3.
print(x / y)

1.6666666666666667


### Type conversion

In [8]:
# convert integer to float
x = 3
y = float(x)
print(y)
print(type(y))

3.0
<class 'float'>


In [9]:
# convert float to integer
x = 3.
y = int(x)
print(y)
print(type(y))

3
<class 'int'>


### Comparison operators

In [10]:
# comparison operators
x = 3
y = 5
print("greater than: ", x > y)
print("greater than or equal to: ", x >= y)
print("less than: ", x < y)
print("less than or equal to: ", x <= y)
print("equal to: ", x == y)
print("not equal to: ", x != y)

greater than:  False
greater than or equal to:  False
less than:  True
less than or equal to:  True
equal to:  False
not equal to:  True


In [13]:
x = 3
y = 3.
x == y

True

## Boolean Variables

### Definition

In [14]:
x = True
y = False
print(type(x))

<class 'bool'>


### Boolean operators

In [15]:
x = True
y = False
print("and: ", x and y)
print("or: ", x or y)
print("not: ", not x)

and:  False
or:  True
not:  False


### Conversion

In [16]:
# convert bool to int
print(int(False))
print(int(True))

0
1


In [17]:
# convert int to bool
print(bool(0))
print(bool(1))

False
True


## String Variables

### Definition

In [18]:
# define string variable
x = "hello"
print(type(x))

<class 'str'>


In [19]:
# get the third character of the string
x = "hello"
y = x[3]
print(y)

l


### String methods

In [20]:
# convert to upper case
"hello".upper()

'HELLO'

In [21]:
# convert to lower case
"HELLO".lower()

'hello'

In [22]:
# replace substring
"hello".replace("llo", "ro")

'hero'

In [23]:
# split string
"hello-world".split("-")

['hello', 'world']

In [24]:
# string concatenation
"hello" + " " + "world"

'hello world'

In [25]:
# example string methods
x = "hello world "
print("capitalize: ", x.capitalize())
print("index: ", x.index("world"))
print("isalpha: ", x.isalpha())
print("isdigit: ", x.isdigit())
print("islower: ", x.islower())
print("isupper: ", x.isupper())
print("lower: ", x.lower())
print("replace: ", x.replace("world", "students"))
print("split: ", x.split(" "))
print("strip: ", x.strip())
print("upper: ", x.upper())

capitalize:  Hello world 
index:  6
isalpha:  False
isdigit:  False
islower:  True
isupper:  False
lower:  hello world 
replace:  hello students 
split:  ['hello', 'world', '']
strip:  hello world
upper:  HELLO WORLD 


### Conversion

In [26]:
# convert int to str
print(str(3))
# convert float to str
print(str(54.3))
# convert bool to str
print(str(True))

3
54.3
True


In [27]:
# convert str to int
print(int("75"))
# convert str to float
print(float("45.2"))
# convert str to bool
print(bool("True"))

75
45.2
True


In [28]:
# try to convert str to int
int("4.5")

ValueError: invalid literal for int() with base 10: '4.5'

## None variables

### Definition

In [29]:
x = None
print(type(x))

<class 'NoneType'>


# Collections

## Lists

### Definition

In [30]:
# assign a list with string variables
cities = ["Ghent", "Brussels", "Antwerp"]

# assign a list with numeric variables
scores = [13, 19, 18, 19, 11, 9]

# assign a list with numeric and string variables
names_and_wages = ["tim", 3003, "john", 1600, "sophie", 1900]

print(type(cities))

<class 'list'>


### Indexing

In [31]:
# get index of element
cities = ["Ghent", "Brussels", "Antwerp"]
print(cities[1])

Brussels


In [32]:
# get index of first element
cities = ["Ghent", "Brussels", "Antwerp"]
print(cities[0])

Ghent


In [33]:
# get index of last element
cities = ["Ghent", "Brussels", "Antwerp"]
print(cities[-1])

Antwerp


In [34]:
# get index of second last element
cities = ["Ghent", "Brussels", "Antwerp"]
print(cities[-2])

Brussels


In [35]:
# get index of first two elements
cities = ["Ghent", "Brussels", "Antwerp"]
print(cities[0:2])

['Ghent', 'Brussels']


In [36]:
# define a string
string = "hello world"

# get the character at index 6
print(string[6])

w


### Operations

In [37]:
# change element
cities = ["Ghent", "Brussels", "Antwerp"]
cities[1] = "Louvain"
print(cities)

['Ghent', 'Louvain', 'Antwerp']


In [38]:
# number of elements
cities = ["Ghent", "Brussels", "Antwerp"]
print(len(cities))

3


In [39]:
# append elements
cities = ["Ghent", "Brussels", "Antwerp"]
cities.append("Louvain")
cities.append("Bruges")
print(cities)

['Ghent', 'Brussels', 'Antwerp', 'Louvain', 'Bruges']


In [40]:
# insert elements
cities = ["Ghent", "Brussels", "Antwerp"]
cities.insert(0, "Louvain")
cities.insert(2, "Bruges")
print(cities)

['Louvain', 'Ghent', 'Bruges', 'Brussels', 'Antwerp']


In [ ]:
# extend list
cities_1 = ["Ghent", "Brussels", "Antwerp"]
cities_2 = ["Leuven", "Bruges"]
cities_1.extend(cities_2)
print(cities_1)

['Ghent', 'Brussels', 'Antwerp', 'Leuven', 'Bruges']


In [41]:
# remove element from list
cities = ["Ghent", "Brussels", "Antwerp"]
cities.remove("Ghent")
print(cities)

['Brussels', 'Antwerp']


In [42]:
# remove element at index from list
cities = ["Ghent", "Brussels", "Antwerp"]
cities.pop(1)
print(cities)

['Ghent', 'Antwerp']


In [43]:
# get index of element 
cities = ["Ghent", "Brussels", "Antwerp"]
idx = cities.index("Brussels")
print(idx)

1


### Nested lists

In [44]:
# nested lists
products = [["samsung", "apple", "nokia"], 
            ["bmw", "mercedes", "audi", "toyota", "renault"],
            ["apple", "banana"]]

print(products[1][2])

audi


## Dictionaries

### Definition

In [45]:
# assigning a dictionary
students_and_scores = {"tom": 13, "sarah": 20, "john": 9}
print(type(students_and_scores))

<class 'dict'>


### Indexing

In [46]:
# get the score of specific student
students_and_scores = {"tom": 13, "sarah": 20, "john": 9}
print(students_and_scores["sarah"])

20


### Operations

In [47]:
# change the value of specific item
students_and_scores = {"tom": 13, "sarah": 20, "john": 9}
students_and_scores["sarah"] = 4
print(students_and_scores)

{'tom': 13, 'sarah': 4, 'john': 9}


In [48]:
# get number of items in dictionary
students_and_scores = {"tom": 13, "sarah": 20, "john": 9}
print(len(students_and_scores))

3


In [49]:
# add new item to dictionary
students_and_scores = {"tom": 13, "sarah": 20, "john": 9}
students_and_scores["lisa"] = 15
print(students_and_scores)

{'tom': 13, 'sarah': 20, 'john': 9, 'lisa': 15}


In [50]:
# remove item from dictionary
students_and_scores = {"tom": 13, "sarah": 20, "john": 9}
students_and_scores.pop("john")
print(students_and_scores)

{'tom': 13, 'sarah': 20}


In [51]:
# get the keys of the dictionary
students_and_scores = {"tom": 13, "sarah": 20, "john": 9}
keys = students_and_scores.keys()
print(keys)

dict_keys(['tom', 'sarah', 'john'])


In [52]:
# get the values of the dictionary
students_and_scores = {"tom": 13, "sarah": 20, "john": 9}
values = students_and_scores.values()
print(values)

dict_values([13, 20, 9])


### Nested dictionaries

In [53]:
# nested dictionary
customer_info = {"tom": {"city": "brussels", "email": "tom@hotmail.com", "age": 24},
                 "sarah": {"city": "Ghent", "email": "sarah@gmail.com", "age": 32},
                 "jack": {"city": "Ghent", "email": "jackjack@gmail.com", "age": 12}}

print(customer_info["tom"]["email"])

tom@hotmail.com


## Tuples

### Definition

In [60]:
# create a tuple with different data types
my_tuple = ("Ghent", 13, 4.20, ["el1", "el2"], {"key_1": 1.0, "key_2": 2.0})

print(type(my_tuple))

<class 'tuple'>


### Indexing

In [61]:
# retrieve the second element
my_tuple = ("Ghent", 13, 4.20, ["el1", "el2"], {"key_1": 1.0, "key_2": 2.0})
print(my_tuple[1])

13


In [62]:
# retrieve the last element
my_tuple = ("Ghent", 13, 4.20, ["el1", "el2"], {"key_1": 1.0, "key_2": 2.0})
print(my_tuple[-1])

{'key_1': 1.0, 'key_2': 2.0}


### Operations

In [63]:
# create a tuple (NOTE: once created, you cannot change any element)
my_tuple = ("Ghent", 13, 13, 4.20, ["el1", "el2"], {"key_1": 1.0, "key_2": 2.0})

In [64]:
# retrieve number of elements
print(len(my_tuple))

6


In [65]:
# retrieve the index of the list in our tuple
print(my_tuple.index(["el1", "el2"]))

4


In [66]:
# retrieve the index of the list in our tuple
print(my_tuple.count(13))

2


In [67]:
# join two tuples
first_tuple = ("Ghent", "Brussels")
second_tuple = ("Antwerp", "Leuven")
new_tuple = first_tuple + second_tuple # alternative notation: my_tuple += my_tuple2 
print(new_tuple)

('Ghent', 'Brussels', 'Antwerp', 'Leuven')


In [68]:
# compare two tuples
first_tuple = ("Ghent", "Brussels")
second_tuple = ("Antwerp", "Leuven")
print(first_tuple == second_tuple)

False


In [69]:
# compare two tuples
first_tuple = ("Ghent", "Antwerp")
second_tuple = ("Antwerp", "Leuven")
print(first_tuple < second_tuple)

False


In [70]:
# other comparisons (NOTE: the comparison is done element by element!)
print((2, 3) == (2, 3))

print((5, 6, 7) < (7, 5, 6))

print((5, 6, 7) > (7, 5, 6))

print((4, 3, 2) <= (4.0, 3.0, 2.0))

True
True
False
True


In the examples above, you compare tuples of numbers using the standard comparison operators. Python runs an **element-by-element comparison**. So, for example: 
- In the first expression above, Python compares the 2 in the left tuple and the 2 in the right one. They’re equal, and Python continues by comparing 3 and 3 to conclude that both tuples are equal.

- In the second expression, Python compares 5 and 7. They’re different. Because 5 is less than 7, this *individual comparison* determines the result of the entire expression, and you get True as a result. If we perform the opposite action, using > instead of <, 5 is not less than 7, so we get False as a result.

- In the last expression, both tuples contain the same values. Because equality is included in the comparison, you get True as a result. **Note** that it can handle with the fact that one tuple uses ``integer`` and the other tuple uses ``float`` notation!

### Nested Tuples

In [ ]:
# nested tuples
nested_tuple = (("Ghent", 6), ("Brussels", 9)) 
print(nested_tuple[0][1])

6


# Conditionals

## If-Else

### Definition

In [71]:
# if-elif-else example
number = 3

if number > 0:
    
    print("this is a positive number")
    
elif number == 0:
    
    print("this number equals zero")
    
else:
    print("this is a negative number")

this is a positive number


### Nested if-else

In [72]:
# nested if-else example
customers = {"Tom": {"mail": True, "phone": False},
             "Julie": {"mail": False, "phone": False},
             "Jasper": {"mail": True, "phone": True}}

contact_customer = "tom"

# check if the customer we want to contact is in our customer list
if contact_customer in customers.keys():
    
    # check if customer wants to be contacted via mail
    if customers[contact_customer]["mail"] == True:
        print("customer wants to be contacted via mail")  
    else:
        print("customer wants not to be contacted via mail")
        
    # check if customer wants to be contacted via phone
    if customers[contact_customer]["phone"] == True:
        print("customer wants to be contacted via phone")  
    else:
        print("customer wants not to be contacted via phone")
        
else:
    
    print("customer not in customer list!")

customer not in customer list!


## For

### Looping through a list

In [73]:
# looping through a range of numbers
for i in range(0, 3):
    print(i)

0
1
2


In [74]:
# looping through a list
customers = ["tom", "sarah", "julie"]
for cust in customers:
    print(cust)

tom
sarah
julie


### Looping through a dictionary

In [75]:
# looping through keys of a dictionary
product_prices = {"xs45321": 420, "xs5620": 690, "xs0909": 2503}

for key in product_prices.keys():
    print(key, ":", product_prices[key])

xs45321 : 420
xs5620 : 690
xs0909 : 2503


In [76]:
# looping through items of a dictionary
product_prices = {"xs45321": 420, "xs5620": 690, "xs0909": 2503}

for key, value in product_prices.items():
    print(key, ":", value)

xs45321 : 420
xs5620 : 690
xs0909 : 2503


## While

### Definition

In [77]:
# example while loop
counter = 0

while counter < 4:
    
    print("counter: ", counter)
    counter = counter + 1       

counter:  0
counter:  1
counter:  2
counter:  3


### Infinite while loop

In [78]:
# example infinite while loop: Do not run this!!!
#counter = 0

#while counter >= 0:

    #counter = counter + 1

### Break and continue

In [79]:
# break
counter = 0

while counter < 6:
    
    print("counter: ", counter)
    counter = counter + 1
    
    if counter == 3:
        break

counter:  0
counter:  1
counter:  2


In [80]:
# continue
counter = 0

while counter < 6:
    
    counter = counter + 1
    
    if counter == 3:
        continue
        
    print("counter: ", counter)

counter:  1
counter:  2
counter:  4
counter:  5
counter:  6


## Try-Except

### Definition

In [81]:
customer_spendings = {"Tom": {"years_customer": 5, "total_spendings": 304},
                  "Julie": {"years_customer": 0, "total_spendings": 1402},
                  "Jack": {"years_customer": 2, "total_spendings": 459}}

for customer, value in customer_spendings.items():
    
    try:
        avg_spending_per_year = value["total_spendings"] / value["years_customer"]
        print(customer, ":", avg_spending_per_year)
    except:
        avg_spending_per_year = value["total_spendings"]
        print(customer, ":", avg_spending_per_year, "for less than 1 year a customer")

Tom : 60.8
Julie : 1402 for less than 1 year a customer
Jack : 229.5


# Reading and Writing Files

## Reading

### General procedure

In [1]:
# open the corpus.txt file into the file object f
f = open("./Data/corpus.txt", "r")

In [2]:
# read the file
text = f.read()
print(text)

this is the first sentence
and this is the second sentence
the third sentence has some more words than the previous sentences
this sentence is the last one


In [3]:
# close the file
f.close()

In [4]:
# inspect object type of text variable
type(text)

str

### Read functions

In [5]:
# open the corpus.txt file into the file object f
f = open("./Data/corpus.txt", "r")

# initialize empty list
lines_container = []

# loop through lines
for line in f:
    # add line to container
    lines_container.append(line)

# loop through container
for line in lines_container:
    print(line)

this is the first sentence

and this is the second sentence

the third sentence has some more words than the previous sentences

this sentence is the last one


In [6]:
# open the corpus.txt file into the file object f
f = open("./Data/corpus.txt", "r")

# read lines into container
container = f.readlines()

print(type(container))
print(len(container))
print(container[0])

<class 'list'>
4
this is the first sentence



In [7]:
# close the file
f.close()

In [8]:
# open the corpus.txt file into the file object f
f = open("./Data/corpus.txt", "r")

# loop through the lines 
for line in f:
    print(line)

this is the first sentence

and this is the second sentence

the third sentence has some more words than the previous sentences

this sentence is the last one


In [9]:
# close the file
f.close()

In [15]:
# open the customers.csv file
f = open("./Data/customers.csv", "r")

# initialize dictionary
customers_dict = dict()


# loop through the lines
for line in f:
    # remove new line 
    line = line.replace("\n", "")
    # split line by separator
    data = line.split(";")
    # create dictionary
    cust_dict = {"name": data[1], "country": data[2], "phone": data[3]}
    # store in customers dict with id as key
    customers_dict[line[0]] = cust_dict
    
# inspect dict
customers_dict

{'2': {'name': 'Thomas', 'country': 'Belgium', 'phone': '0456203495'},
 '4': {'name': 'Sarah', 'country': 'Belgium', 'phone': '0405010034'},
 '6': {'name': 'Julie', 'country': 'France', 'phone': '04050103003'},
 '3': {'name': 'Patrick', 'country': 'France', 'phone': '040502010'}}

In [16]:
# close the file
f.close()

### With

In [17]:
# use the with statement
with open("./Data/corpus.txt", "r") as f:
    text = f.read()

## Writing Files

### General procedure

In [18]:
# initialize a string
string = "this is some random string I want to store"

In [19]:
with open("./Data/my_random_string.txt", "w") as f:
    f.write(string)

You will now see the my_random_string.txt file appear in your **Data folder**. Go check if this is the case!

### Write functions

In [20]:
# initialize a list you want to store
customers  = ['Tom', 'Charlotte', 'Lyam', 'Patrick', 'Matts', 'Lesley']

In [21]:
with open("./Data/my_customers.txt", "w") as f:
    f.writelines(customers)

In [22]:
# initialize a list you want to store
customers  = ['Tom\n', 'Charlotte\n', 'Lyam\n', 'Patrick\n', 'Matts\n', 'Lesley\n']

In [23]:
with open("./Data/my_customers_2.txt", "w") as f:
    f.writelines(customers)

In [24]:
# initialize a dictionary you want to store
customer_info  = [{"name": "Tom", "country": "Belgium", "customer_since": "05/03/1997"},
                  {"name": "Matts", "country": "United States", "customer_since": "14/09/2003"}, 
                  {"name": "Lesley", "country": "France", "customer_since": "01/11/1993"},
                  {"name": "Catherine", "country": "Belgium", "customer_since": "25/04/2005"}]

In [25]:
# open the file
with open("./Data/my_customers_3.txt", "w") as f:

    # loop through objects
    for customer in customer_info:
        
        # get the name
        name = customer["name"]
        # get the country
        country = customer["country"]
        # get the start date
        start_date = customer["customer_since"]
        
        # write data to file and seperate by ;
        f.write(name)
        f.write(";")
        f.write(country)
        f.write(";")
        f.write(start_date)
        f.write("\n")

In the end, you will find the three newly created customer ``.txt`` files in your **Data folder**. Go check if this is the case!

## Functions

### Definition

In [26]:
# built in functions
print("hallo")
print(type(3.0))
print(float(2))
print(str(2))
print(bool(0))
print(list())
print(dict())

hallo
<class 'float'>
2.0
2
False
[]
{}


### Parameters

In [27]:
# define a function which adds a constant to a number
def add_constant_to_number(number, constant):
    
    # calculate result
    result = number + constant
    
    # return result
    return(result)

In [28]:
# call the function for a specific number and constant
result = add_constant_to_number(number=15, constant=3)
print(result)

18


In [29]:
# define a function that will print the elements of a list
def print_elements_list(elements):
    for el in elements:
        print(el)

In [30]:
# define a list of elements
e = ["belgium", "france", "germany"]
# call function on this list
print_elements_list(e)

belgium
france
germany


In [31]:
# define a function that divides a numerator by denominator
def division(numerator, denominator):
    
    return(numerator / denominator)

In [32]:
# call the function with parameter values at correct place
div = division(4., 2.)
print(div)

2.0


In [33]:
# call the function with parameter values not at correct place
div = division(2., 4.)
print(div)

0.5


In [34]:
# call the function with parameter names and values specified
div = division(denominator=2., numerator=4.)
print(div)

2.0


In [35]:
# define function which prints a customer's name
def print_name(name="unknown"):
    
    print("the customer's name is: " + name)

In [36]:
# call function with parameter specified
print_name(name="jack")

the customer's name is: jack


In [37]:
# call function with no parameter specified
print_name()

the customer's name is: unknown


### Return

In [38]:
# define function with multiple return statements
def divide_and_sum(number, constant_1, constant_2):
    
    # divide number by constant_1
    result_1 = number / constant_1
    return(result_1)

    # add constant_2 to result_1
    result_2 = result_1 + constant_2
    return(result_2)

In [39]:
# call function 
result = divide_and_sum(number=10, constant_1=5, constant_2=2)
print(result)

2.0


### Flexible Functions

In [40]:
def print_args(*args):
   # loop through non-keyword arguments (stored as a tuple)
   for arg in args:
      print(arg)
      
print_args(1, 2, 3)

1
2
3


In [41]:
def print_kwargs(**kwargs):
   # loop through keyword arguments (stored as a dictionary)
   for key, value in kwargs.items():
      print("{key}: {value}".format(key=key, value=value))

print_kwargs(a=1, b=2, c=3)

a: 1
b: 2
c: 3


In [42]:
def print_args_kwargs(*args, **kwargs):
   # loop through non-keyword arguments (stored as a tuple)
   for arg in args:
      print("Non-keyword argument: {arg}".format(arg=arg))
            
   # loop through keyword arguments (stored as a dictionary)
   for key, value in kwargs.items():
      print("Keyword argument: {key}={value}".format(key=key, value=value))

print_args_kwargs(1, 2, 3, a=1, b=2, c=3)

Non-keyword argument: 1
Non-keyword argument: 2
Non-keyword argument: 3
Keyword argument: a=1
Keyword argument: b=2
Keyword argument: c=3


# Modules

## Usage

In [ ]:
# install package from within Jupyter Notebook
# NOTE: replace package_name by the name of the package you want to install!
!pip install package_name
#in VSCode it better to use: %pip install package_name

ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os
Note: you may need to restart the kernel to use updated packages.


In [43]:
# import entire module
import os

In [ ]:
# use the makedirs function from the os module
os.makedirs("./test", exist_ok=True)

In [123]:
# import the function from the module
from os import listdir

In [124]:
# use the listdir function from the os module
listdir("./")

['prep',
 '.DS_Store',
 '[L02]Python.ipynb',
 'Session2_Python_2025.pptx',
 'Data',
 '~$Session2_Python_2025.pptx']

In [ ]:
# define an alias for the package numpy (if not installed run !pip or %pip install numpy)
import numpy as np

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 30.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


# Numpy

## Definition

In [ ]:
# import the numpy package
import numpy as np 

## Multi-dimensional array

### Creation

In [ ]:
# define a 1D array
arr = np.array([3, 4, 1])

In [ ]:
print(arr)

[3 4 1]


In [ ]:
# define a 2D array
arr = np.array([[1, 3, 0], [3, 2, 5]])

In [ ]:
print(arr)

[[1 3 0]
 [3 2 5]]


In [ ]:
# create an array full of zeros with shape (2, 3)
zeros = np.zeros(shape=(2, 3))

print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# create an array full of ones with shape (1, 3)
ones = np.ones(shape=(1, 3))

print(ones)

[[1. 1. 1.]]


In [ ]:
# create a matrix full of 5 with the shape (2, 2)
fives = np.full(fill_value=5, shape=(2, 2))

print(fives)

[[5 5]
 [5 5]]


In [ ]:
# create an array of random numbers between 0 and 1 of shape (2, 2)
random_floats = np.random.random(size=(2, 2))

print(random_floats)

[[0.96972104 0.52447162]
 [0.752321   0.3225871 ]]


In [ ]:
# create an array of random integers between 0 and 10 of shape (2, 2)
random_ints = np.random.randint(low=0, high=10, size=(2, 2))

print(random_ints)

[[5 0]
 [9 9]]


In [ ]:
# create an array of random normal numbers with mean 0 and stdev 1 of shape (2, 2)
random_normals = np.random.normal(loc=0, scale=1, size=(2, 2))

print(random_normals)

[[-2.19480183  0.68834926]
 [ 1.12353551 -0.9143659 ]]


In [ ]:
# define another 2D array 
arr = np.array([[1, 3, 0], [3, 2, 5], [5, 7, 1], [3, 4, 1]])

print(arr)

# get the shape of the array
arr.shape

[[1 3 0]
 [3 2 5]
 [5 7 1]
 [3 4 1]]


(4, 3)

### Indexing

In [ ]:
# define an array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# access the element on the first row and second column
arr[0, 1]

2

In [ ]:
# access the elements on the first row from the first column untill the second column
arr[1, 0:2]

array([4, 5])

### Mathematical Operations

In [ ]:
# initialize two arrays
arr_1 = np.array([[1, 3], [-2, 5]])
arr_2 = np.array([[2, 4], [3, -1]])

print(arr_1)
print("\n")
print(arr_2)

[[ 1  3]
 [-2  5]]


[[ 2  4]
 [ 3 -1]]


In [ ]:
# perform element-wise summation
arr_3 = arr_1 + arr_2

print(arr_3)

[[3 7]
 [1 4]]


In [ ]:
# perform element-wise subtraction
arr_4 = arr_1 - arr_2

print(arr_4)

[[-1 -1]
 [-5  6]]


In [ ]:
# perform element-wise multiplication
arr_5 = arr_1 * arr_2

print(arr_5)

[[ 2 12]
 [-6 -5]]


In [ ]:
arr_5 = arr_1 + np.array([2, 1, 5])

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [ ]:
# broadcasting
arr_4 = arr_1 + np.array([3, 2])

print(arr_4)

[[4 5]
 [1 7]]


In [ ]:
# add scalar to array
arr_1 + 2

array([[3, 5],
       [0, 7]])

In [ ]:
# add vector to array
arr_1 + np.array([2, 3])

array([[3, 6],
       [0, 8]])

In [ ]:
a = np.zeros(shape=(2, 3, 2))
b = np.ones(shape=(2))
a + b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
# do matrix mulitplication between arr_1 and arr_2
arr = np.dot(arr_1, arr_2)

print(arr)

[[ 11   1]
 [ 11 -13]]


In [ ]:
# take the sum along the second dimension
np.sum(arr_1, axis=1)

array([4, 3])

In [ ]:
# take the mean along the first dimension
np.mean(arr_1, axis=0)

array([-0.5,  4. ])

In [ ]:
# take the maxium of the entire array
np.max(arr_1)

5

In [ ]:
# take the minimum along the first dimension
np.min(arr_1, axis=0)

array([-2,  3])

## Array Manipulation

In [ ]:
# define array
arr_1 = np.array([1, 2, 3, 4])

# reshape array
# NOTE (2026 update): np.reshape()'s second argument was renamed from `newshape` to `shape`
# in NumPy 2.1+, and the old `newshape` keyword was later removed entirely (raises TypeError
# on NumPy 2.4+, the version this notebook now runs against).
arr_2 = np.reshape(arr_1, shape=(2, 2))

# check
arr_2

In [ ]:
# define array
arr_1 = np.array([[1, 2], [3, 4]])

# check
print(arr_1)

[[1 2]
 [3 4]]


In [ ]:
# transpose array
arr_2 = np.transpose(arr_1)

# check
print(arr_2)

[[1 3]
 [2 4]]


In [ ]:
# define array
arr_1 = np.zeros(shape=(2, 3))
arr_2 = np.ones(shape=(1, 3))

# concatenate along first dimension
arr_3 = np.concatenate([arr_1, arr_2], axis=0)

# check
arr_3

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.]])